[package]
name = "rule-30-solver-validator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "validator"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }

dirs = { workspace = true }

tracing-subscriber = { workspace = true }
tracing = { workspace = true }

threadpool = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

tempfile = "3.13.0"
memmap2 = "0.9.5"

rule-30-solver-neuron = { path = "../base" }
